### ISSUE TITLE
500 internal error when posting

### ISSUE THREAD

**Issue by tingwei628** [studiodev/Mocky#10] opened 2015-10-02 01:21 UTC
I want to create a API which will get me a response as JSON.

But, an error occured

**Comment by studiodev** [comment] 2015-10-02 07:06
You're right, something got wrong since this morning :(

I will check that tonight of tomorrow.

**Comment by user392919** [comment] 2015-10-02 07:17
Also getting the `An error occured... please retry !` when try to generate HTTP response

**Comment by studiodev** [comment] 2015-10-02 07:44
I'm on the problem. It seems that the connection if refused from MongoLab (my db hoster)

**Comment by studiodev** [comment] 2015-10-02 08:36
Sorry guys but I cannot fix the problem without rewriting a big part of the app (new Mongodb version -> need to upgrade mongo version -> need to update play version).

I will try to do that this evening.

**Comment by studiodev** [comment] 2015-10-03 15:27
The problem is now fixed, the app run fixed.

Sorry for this unexpected maintenance, MongoLab has updated all its database to Mongo 3.0, and nothing in the app was compatible. Now all should be fine for the next years :)

**Closed by studiodev** 2015-10-03 15:27 UTC

**Comment by tingwei628** [comment] 2015-10-04 14:30
Thanks, @studiodev

**Comment by nreward360** [comment] 2019-09-23 07:38
An error occured... please retry !
the same error is again coming
@julien-lafont
